defaults: &defaults
  twitter:
    oauth_token: <%= ENV['TWITTER_OAUTH_TOKEN'] %>
    oauth_secret: <%= ENV['TWITTER_OAUTH_SECRET'] %>
    consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  aws:
    s3_key: <%= ENV['AWS_S3_KEY'] %>
    s3_secret: <%= ENV['AWS_S3_SECRET'] %>
    bucket: <%= ENV['AWS_BUCKET'] %>
  pusher:
    app_id: <%= ENV['PUSHER_APP_ID'] %>
    key: <%= ENV['PUSHER_KEY'] %>
    secret: <%= ENV['PUSHER_SECRET'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
